import { Geist, Geist_Mono } from "next/font/google";
import { ShopContextProvider } from '@/app/contexts/ShopContext'
import "./globals.css";
import Navbar from '@/components/Navbar'
import Footer from "@/components/Footer"

import { Syne } from "next/font/google";

const syne = Syne({
  subsets: ["latin"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={syne.className}>
      <body className="flex flex-col min-h-screen"> 
        <ShopContextProvider> 
          <Navbar/>
            <main className="flex-1">
              {children}
            </main>
          <Footer/>
        </ShopContextProvider>
      </body>
    </html>
  );
}
